### ISSUE TITLE
Program does not work :/

### ISSUE THREAD

**Issue by mbledkowski** [Geremia/LibgenBulkUpload#2]
```
Specified directories:
/home/mble/Downloads/Books/
/home/mble/Downloads/Books/uploaded/
/home/mble/Downloads/Books/rejected/

Traceback (most recent call last):
  File "/home/mble/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mble/Downloads/../Code/repos/misc/LibgenBulkUpload/upload.py", line 57, in <module>
    login()
  File "/home/mble/Downloads/../Code/repos/misc/LibgenBulkUpload/upload.py", line 36, in login
    driver = webdriver.Firefox()
  File "/home/mble/.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 176, in __init__
    self.service.start()
  File "/home/mble/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

```

**Comment by mbledkowski** [comment]
Nevermind, `sudo pacman -S geckodriver` helped
